// Menu card data for Swaada Caterings & Services
// All content from original menu cards, rebranded for Swaada

export interface MenuCard {
    id: string;
    title: string;
    emoji: string;
    description: string;
    color: string;
    bgGradient: string;
    menus: MenuVariant[];
    includes: string[];
}

export interface MenuVariant {
    name: string;
    items: string[];
}

export const SWAADA_INFO = {
    name: "Swaada Caterings & Services",
    tagline: "Every Occasion, Perfectly Served",
    phone1: "7892861158",
    phone2: "8105758067",
    email: "hello.swaadacaterings@gmail.com",
    website: "www.swaadacaterers.in",
    address: "Bengaluru, Karnataka",
};

export const menuCards: MenuCard[] = [
    {
        id: "andhra",
        title: "Andhra Menu",
        emoji: "🌶️",
        description: "Authentic Andhra-style feast with bold spices and traditional flavors",
        color: "#C0392B",
        bgGradient: "from-red-700 to-orange-600",
        includes: [
            "Melamine Plates & Spoon",
            "Disposable cups for Water & Sweet",
            "Tissue Paper, Sweet Saunf, Mineral Water",
            "Food served hot in chafing dishes",
            "Buffet Setup with frill cloth",
            "OR Banana Leaf Service",
        ],
        menus: [
            {
                name: "Andhra Menu I",
                items: [
                    "Rumali Roti / Poori / Chapathi",
                    "Paneer Curry / Chole Masala / Mixed Veg Curry",
                    "Veg Biryani / Puliyogare",
                    "Raitha",
                    "White Rice",
                    "Andhra Pappu – Tomato / Palak",
                    "Sambar / Rasam",
                    "Aloo Fry / Stuffed Brinjal / Beans Carrot Palya",
                    "Masala Vada / Chilly Bajji",
                    "Curd / Curd Rice",
                    "Papad",
                    "Pickle (Gongura)",
                    "Gulab Jamoon / Gajjar Halwa / Ladoo / Badusha / Jangiri / Dal Obattu",
                    "Ice Cream / Payasam",
                ],
            },
            {
                name: "Andhra Menu II",
                items: [
                    "Rumali Roti / Poori / Chapathi",
                    "Paneer Curry / Chole Masala / Mixed Veg Curry",
                    "Veg Biryani / Puliyogare",
                    "Raitha",
                    "White Rice",
                    "Dal Powder",
                    "Ghee",
                    "Andhra Pappu – Tomato / Palak / Mango",
                    "Sambar",
                    "Rasam",
                    "Stuffed Brinjal Masala / Beans Carrot Palya",
                    "Bendi Fry / Potato Fry",
                    "Masala Vada / Chilly Bajji",
                    "Curd / Curd Rice",
                    "Gongura Pickle / Avakkai Pickle",
                    "Papad",
                    "Gulab Jamoon / Gajjar Halwa / Ladoo / Badusha / Jangiri / Dal Obattu",
                    "Ice Cream / Payasam",
                ],
            },
            {
                name: "Andhra Menu III",
                items: [
                    "Rumali Roti / Poori / Chapathi",
                    "Paneer Curry / Chole Masala / Mixed Veg Curry",
                    "Veg Biryani / Puliyogare",
                    "Raitha",
                    "White Rice",
                    "Dal Powder",
                    "Ghee",
                    "Andhra Pappu – Tomato / Palak / Mango",
                    "Sambar",
                    "Rasam",
                    "Stuffed Brinjal Masala / Beans Carrot Palya",
                    "Bendi Fry / Potato Fry",
                    "Masala Vada / Chilly Bajji",
                    "Fryums",
                    "Papad",
                    "Curd / Curd Rice",
                    "Gongura Pickle / Avakkai Pickle",
                    "Tomato Roti Pachadi / Beerakai Pachadi",
                    "Shevagi Payasam",
                    "Gulab Jamoon / Gajjar Halwa / Ladoo / Badusha / Jangiri",
                    "Dal Obattu / Coconut Obattu",
                    "Ice Cream – Vanilla / Butter Scotch",
                    "Banana",
                    "Beeda",
                ],
            },
        ],
    },
    {
        id: "birthday",
        title: "Birthday Menu",
        emoji: "🎂",
        description: "Fun and festive birthday spreads with starters, mains, and desserts",
        color: "#8E44AD",
        bgGradient: "from-purple-700 to-pink-600",
        includes: [
            "Melamine Plates & Spoon",
            "Disposable cups for Water & Sweet",
            "Tissue Paper, Sweet Saunf, Mineral Water",
            "Food served hot in chafing dishes",
            "Buffet Setup with frill cloth",
            "OR Banana Leaf Service",
        ],
        menus: [
            {
                name: "Birthday Menu 1",
                items: [
                    "Any 1 Soup: Mix Veg / Tomato / Sweet Corn",
                    "Any 1 Welcome Drink: Lemonade / Orangeade",
                    "Any 2 Starters: Veg Roll / Schezwan Roll / Mini Samosa / Cheese Balls / Nuggets / Veg Cutlet / French Fries / Aloo Bonda / Baby Corn Manchurian / Gobi Manchurian / Gobi 65 / Aloo Kabab",
                    "Any 2 Heavy Snacks: Batura-Chole Masala / Rumali Roti-Paneer Curry / Parota-Veg Kurma / Veg Pulav-Raitha / Veg Fried Rice / Veg Noodles / Pasta / Pani Puri / Dahi Puri / Masala Poori / Mini Idly-Sambar / Mini Masala Dosa",
                    "Any 1 Sweet: Jamoon / Rasagullah / Gajjar Halwa / Malai Sandwich",
                    "Any 1 Ice Cream: Vanilla / Butter Scotch / Strawberry",
                ],
            },
            {
                name: "Birthday Menu 2 (North-South)",
                items: [
                    "Soup / Welcome Drink: Mix Veg / Tomato / Sweet Corn / Lemonade / Orangeade / Fruit Mocktail",
                    "1 Veg Starter: Veg Roll / Schezwan Roll / Mini Samosa / Baby Corn Manchurian / Gobi Manchurian",
                    "1 Indian Bread: Rumali Roti / Methi Chapathi / Poori / Battura",
                    "1 Veg Curry: Paneer Pasantha / Paneer Bahari / Mutter Paneer / Paneer Butter Masala / Chole Masala",
                    "1 Dry Veg: Mix Veg Dry / Aloo Jeera Dry / Aloo Mutter Dry / Beans Carrot / Cabbage Mutter",
                    "1 Flavoured Rice: Veg Pulav / Peas Pulav / Veg Biryani",
                    "Raitha, White Rice, Dal Fry / Dal Makhni, Rasam, Sambar, Curd, Dahi Vada, Curd Rice, Papad, Pickle",
                    "1 Salad: Green Salad / Finger Salad / Kosambari",
                    "1 Sweet: Gulab Jamoon / Gajjar Halwa / Rasagullah / Malai Sandwich",
                    "1 Ice Cream: Vanilla / Butter Scotch / Strawberry",
                ],
            },
        ],
    },
    {
        id: "brahmin",
        title: "Brahmin Menu",
        emoji: "🙏",
        description: "Pure vegetarian Brahmin style  with or without onion & garlic",
        color: "#27AE60",
        bgGradient: "from-green-700 to-teal-600",
        includes: [
            "Melamine Plates & Spoon",
            "Disposable cups for Water & Sweet",
            "Tissue Paper, Sweet Saunf, Mineral Water",
            "Food served hot in chafing dishes",
            "Buffet Setup with frill cloth",
            "OR Banana Leaf Service",
        ],
        menus: [
            {
                name: "Brahmin Breakfast Menu",
                items: [
                    "Kesari",
                    "Idly",
                    "Vada",
                    "Pongal / Karabath",
                    "Chutney",
                    "Sambar",
                    "Coffee / Tea",
                ],
            },
            {
                name: "Brahmin Lunch Menu (Without Onion & Garlic)",
                items: [
                    "Pal Payasam / Semia Payasam / Dal Payasam",
                    "Curd Pachadi / Sweet Pachadi",
                    "Kadala Paruppu Kosmalli / Kosambari",
                    "Beans Poriyal / Beans Usili",
                    "Potato Fry",
                    "Curd Vada",
                    "Puliyogare / Lime Rice / Coconut Rice",
                    "Ghee",
                    "White Rice",
                    "Sambar",
                    "Tomato Rasam",
                    "Appalam",
                    "Curd",
                    "Pickle",
                    "Jangiri / Ladoo / Badusha / Mysore Pak / Gulab Jamoon / Carrot Halwa",
                ],
            },
        ],
    },
    {
        id: "breakfast",
        title: "Breakfast Menu",
        emoji: "☕",
        description: "Fresh and hot South Indian breakfast spreads for morning events",
        color: "#E67E22",
        bgGradient: "from-amber-600 to-yellow-500",
        includes: [
            "Melamine Plates & Spoon",
            "Disposable cups for Water & Sweet",
            "Tissue Paper, Sweet Saunf, Mineral Water",
            "Food served hot in chafing dishes",
            "Buffet Setup with frill cloth",
            "OR Banana Leaf Service",
        ],
        menus: [
            {
                name: "Breakfast Menu I",
                items: [
                    "Kesari",
                    "Idly",
                    "Vada",
                    "Pongal / Karabath / Bisibelebath",
                    "Chutney",
                    "Sambar",
                    "Coffee",
                ],
            },
            {
                name: "Breakfast Menu II",
                items: [
                    "Kesari",
                    "Idly",
                    "Vada",
                    "Pongal / Karabath / Bisibelebath",
                    "Masala Dosa / Poori",
                    "Coconut Chutney",
                    "Tomato Chutney",
                    "Idly Podi",
                    "Tiffin Sambar",
                    "Coffee",
                ],
            },
        ],
    },
    {
        id: "karnataka",
        title: "Karnataka Menu",
        emoji: "🏰",
        description: "Traditional Karnataka-style feast with authentic local flavors",
        color: "#D4AC0D",
        bgGradient: "from-yellow-600 to-amber-500",
        includes: [
            "Melamine Plates & Spoon",
            "Disposable cups for Water & Sweet",
            "Tissue Paper, Sweet Saunf, Mineral Water",
            "Food served hot in chafing dishes",
            "Buffet Setup with frill cloth",
            "OR Banana Leaf Service",
        ],
        menus: [
            {
                name: "Karnataka Style Menu",
                items: [
                    "Salt, Pickle",
                    "Bele Kosambari / Corn Kosambari",
                    "Beans Palya / Cabbage Palya / Aloo Fry / Thondaikai Fry",
                    "Rumali Roti / Poori / Chapathi",
                    "Veg Gravy: Paneer Curry / Mix Veg Kuruma / Channa Masala",
                    "Veg Biryani / Veg Pulav / Bisibelebath / Vaangibath / Puliyogare",
                    "Raitha / Boondi",
                    "White Rice",
                    "Sambar",
                    "Rasam",
                    "Masala Vada / Chilly Baji / Pakkoda",
                    "Curd / Curd Rice",
                    "Papad",
                    "Sabbagi Payasam / Semia Payasam / Dal Payasam",
                    "Sweet: Jamoon / Gajjar Halwa / Ladoo / Dal Obattu",
                    "Ice Cream – Vanilla",
                    "Beeda",
                    "Water Bottle",
                ],
            },
        ],
    },
    {
        id: "marriage",
        title: "Marriage Menu",
        emoji: "💍",
        description: "Grand wedding feast with starters, mains, sweets and more",
        color: "#C0392B",
        bgGradient: "from-red-800 to-rose-600",
        includes: [
            "Melamine Plates & Spoon",
            "Disposable cups for Water & Sweet",
            "Tissue Paper, Sweet Saunf, Mineral Water",
            "Food served hot in chafing dishes",
            "Buffet Setup with frill cloth",
            "OR Banana Leaf Service",
        ],
        menus: [
            {
                name: "Veg Starters",
                items: [
                    "Veg Roll / Schezwan Roll / Mini Samosa / Cheese Ball",
                    "Baby Corn Manchurian / Paneer Manchurian / Gobi Manchurian",
                    "Gobi Kabab / Baby Corn Kabab / Aloo Kabab",
                    "Chilli Gobi / Chilli Paneer / Chilli Baby Corn",
                    "Welcome Drink / Soup: Lemonade / Orangeade / Soft Drink / Tomato Soup / Mixed Veg Soup / Sweet Corn Soup",
                ],
            },
            {
                name: "Chat & Main Course",
                items: [
                    "Chat Items / Dosa Counter: Pani Puri / Dahi Puri / Masala Puri / Bhel Puri",
                    "Indian Bread: Rumali Roti / Masala Chapathi / Methi Chapathi / Plain Chapathi / Poori / Battura",
                    "Veg Gravy: Paneer Pasantha / Mutter Paneer / Paneer Bahari / Paneer Butter Masala / Chole Masala / Veg Kurma / Mixed Veg Curry / Mixed Veg Kofta Curry",
                    "Dry Veg: Aloo Mutter / Aloo Gobi / Aloo Jeera / Aloo Capsicum / Kadai Veg / Beans Carrot Palya / Cabbage Mutter Palya",
                    "Flavoured Rice: Veg Pulav / Peas Pulav / Veg Biryani / Ghee Rice / Bisibelebath",
                    "Raitha: Mix Veg / Onion / Cucumber / Karaboondi",
                    "White Rice, Dal Fry / Dal Makhni / Sambar / Rasam",
                    "Curd / Curd Rice with Fruits / Dahi Vada",
                    "Papad, Pickle",
                ],
            },
            {
                name: "Salad, Sweets & Desserts",
                items: [
                    "Salad: Green Salad / Finger Salad / Kosambari",
                    "Sweet: Gulab Jamoon / Rasagullah / Gajjar Halwa / Rasamalai / Chumchum / Malai Sandwich",
                    "Ice Cream: Vanilla / Butter Scotch / Strawberry",
                    "Beeda",
                ],
            },
            {
                name: "Breakfast Menu 1",
                items: [
                    "Kesari",
                    "Idly",
                    "Vada",
                    "Pongal / Karabath / Bisibelebath",
                    "Chutney",
                    "Sambar",
                    "Coffee / Tea",
                ],
            },
            {
                name: "Breakfast Menu 2",
                items: [
                    "Kesari",
                    "Idly",
                    "Vada",
                    "Pongal / Karabath / Bisibelebath",
                    "Poori / Dosa – Live Counter",
                    "Coconut Chutney",
                    "Tomato Chutney",
                    "Sambar",
                    "Idly Milagaipodi",
                    "Coffee / Tea",
                ],
            },
            {
                name: "Lunch Menu",
                items: [
                    "Poori / Rumali Roti / Chapathi",
                    "Paneer Curry / Mix Veg Kurma / Channa Masala",
                    "Veg Biryani / Veg Pulav / Puliyogare / Vaangibath / Bisibelebath",
                    "Raitha / Chutney / Karaboondi",
                    "White Rice",
                    "Sambar",
                    "Rasam",
                    "Beans Carrot Palya / Cabbage Mutter Palya",
                    "Potato Fry / Dondakai Fry / Bendi Fry",
                    "Masala Vada / Chilly Bajji / Onion Pakkoda / Madhur Vada",
                    "Curd / Curd Rice",
                    "Papad, Pickle",
                    "Corn Kosambari / Bele Kosambari",
                    "Semia Payasam",
                    "Dal Obattu with Ghee",
                    "Gulab Jamoon / Carrot Halwa / Ladoo / Badusha / Jangiri / Mysore Pak",
                    "Banana, Beeda",
                    "Ice Cream",
                    "Water Bottles 300ml",
                ],
            },
        ],
    },
    {
        id: "north-south",
        title: "North & South Menu",
        emoji: "🍱",
        description: "Best of both worlds – North Indian and South Indian fusion menus",
        color: "#2980B9",
        bgGradient: "from-blue-700 to-indigo-600",
        includes: [
            "Melamine Plates & Spoon",
            "Disposable cups for Water & Sweet",
            "Tissue Paper, Sweet Saunf, Mineral Water",
            "Food served hot in chafing dishes",
            "Buffet Setup with frill cloth",
            "OR Banana Leaf Service",
        ],
        menus: [
            {
                name: "North & South Menu 1",
                items: [
                    "Rumali Roti / Methi Chapathi / Poori / Battura",
                    "Paneer Curry / Mixed Veg Curry / Chole Masala / Aloo Gobi Mutter Gravy",
                    "Veg Pulav / Peas Pulav / Veg Biryani / Ghee Rice / Bisibelebath / Vaangibath",
                    "Raitha / Veg Kurma / Karaboondi / Chutney",
                    "White Rice",
                    "Rasam / Dal Fry",
                    "Papad, Pickle",
                    "Gulab Jamoon / Gajjar Halwa / Rasagullah / Malai Sandwich",
                ],
            },
            {
                name: "North & South Menu 2",
                items: [
                    "Rumali Roti / Methi Chapathi / Poori / Battura",
                    "Paneer Curry / Mixed Veg Curry / Chole Masala / Aloo Gobi Mutter Gravy",
                    "Veg Pulav / Peas Pulav / Veg Biryani / Ghee Rice / Bisibelebath / Vaangibath",
                    "Raitha / Veg Kurma / Karaboondi / Chutney",
                    "White Rice",
                    "Rasam / Dal Fry",
                    "Curd / Curd Rice / Dahi Vada",
                    "Papad, Pickle",
                    "Gulab Jamoon / Gajjar Halwa / Rasagullah / Malai Sandwich",
                ],
            },
            {
                name: "North & South Menu 3",
                items: [
                    "Rumali Roti / Methi Chapathi / Poori / Battura",
                    "Paneer Curry / Mixed Veg Curry / Chole Masala / Aloo Gobi Mutter Gravy",
                    "Veg Pulav / Peas Pulav / Veg Biryani / Ghee Rice / Bisibelebath / Vaangibath",
                    "Raitha / Veg Kurma / Karaboondi / Chutney",
                    "White Rice",
                    "Rasam / Dal Fry",
                    "Aloo Jeera Dry / Aloo Gobi / Aloo Capsicum / Kadai Veg Dry / Aloo Fry / Beans Carrot",
                    "Curd / Curd Rice / Dahi Vada",
                    "Papad, Pickle",
                    "Gulab Jamoon / Gajjar Halwa / Rasagullah / Malai Sandwich",
                    "Ice Cream",
                ],
            },
            {
                name: "North & South Menu 4",
                items: [
                    "Starters: Veg Roll / Schezwan Roll / Mini Samosa / Cheese Balls / Baby Corn / Gobi Manchurian",
                    "Rumali Roti / Methi Chapathi / Poori / Battura",
                    "Paneer Curry / Mixed Veg Curry / Chole Masala / Aloo Gobi Mutter Gravy",
                    "Veg Pulav / Peas Pulav / Veg Biryani / Ghee Rice / Bisibelebath / Vaangibath",
                    "Raitha / Veg Kurma / Karaboondi / Chutney",
                    "White Rice",
                    "Dal Fry / Dal Makhni",
                    "Sambar / Rasam",
                    "Aloo Jeera Dry / Aloo Gobi / Aloo Capsicum / Kadai Veg Dry / Aloo Fry / Beans Carrot",
                    "Curd / Curd Rice / Dahi Vada",
                    "Papad, Pickle",
                    "Green Salad",
                    "Gulab Jamoon / Gajjar Halwa / Rasagullah / Malai Sandwich",
                    "Ice Cream",
                ],
            },
            {
                name: "North & South Menu 5",
                items: [
                    "Soup / Welcome Drink: Tomato Soup / Sweet Corn Veg Soup / Mixed Veg Soup / Fruit Mocktail",
                    "Starters: Veg Roll / Schezwan Roll / Mini Samosa / Cheese Balls / Baby Corn / Gobi Manchurian",
                    "Rumali Roti / Methi Chapathi / Poori / Battura",
                    "Paneer Curry / Mixed Veg Curry / Chole Masala / Aloo Gobi Mutter Gravy",
                    "Veg Pulav / Peas Pulav / Veg Biryani / Ghee Rice / Bisibelebath / Vaangibath",
                    "Raitha / Veg Kurma / Karaboondi / Chutney",
                    "White Rice",
                    "Dal Fry / Dal Makhni",
                    "Sambar / Rasam",
                    "Aloo Jeera Dry / Aloo Gobi / Aloo Capsicum / Kadai Veg Dry / Aloo Fry / Beans Carrot",
                    "Curd / Curd Rice / Dahi Vada",
                    "Papad, Pickle",
                    "Green Salad",
                    "Gulab Jamoon / Gajjar Halwa / Rasagullah / Malai Sandwich",
                    "Ice Cream",
                    "Paan",
                    "Water Bottles 300ml",
                ],
            },
        ],
    },
    {
        id: "north-indian",
        title: "North Indian Menu",
        emoji: "🫓",
        description: "Rich and flavorful North Indian cuisine for all occasions",
        color: "#E74C3C",
        bgGradient: "from-orange-700 to-red-600",
        includes: [
            "Melamine Plates & Spoon",
            "Disposable cups for Water & Sweet",
            "Tissue Paper, Sweet Saunf, Mineral Water",
            "Food served hot in chafing dishes",
            "Buffet Setup with frill cloth",
            "OR Banana Leaf Service",
        ],
        menus: [
            {
                name: "North Indian Menu 1",
                items: [
                    "Rumali Roti / Methi Chapathi / Poori / Battura",
                    "Paneer Curry / Mixed Veg Curry / Chole Masala / Rajma Masala",
                    "Aloo Mutter Dry / Aloo Gobi Dry / Aloo Capsicum Dry / Aloo Jeera Dry / Kadai Veg Dry",
                    "Veg Pulav / Peas Pulav / Jeera Pulav / Veg Biryani",
                    "Raitha",
                    "White Rice",
                    "Dal Fry / Dal Makhni",
                    "Papad – North Indian",
                    "Pickle",
                    "Gulab Jamoon / Gajjar Halwa / Rasgullah / Malai Sandwich",
                ],
            },
            {
                name: "North Indian Menu 2",
                items: [
                    "Rumali Roti / Methi Chapathi / Poori / Battura",
                    "Paneer Curry / Mixed Veg Curry / Chole Masala / Rajma Masala",
                    "Aloo Mutter Dry / Aloo Gobi Dry / Aloo Capsicum Dry / Aloo Jeera Dry / Kadai Veg Dry",
                    "Veg Pulav / Peas Pulav / Jeera Pulav / Veg Biryani",
                    "Raitha",
                    "White Rice",
                    "Dal Fry / Dal Makhni",
                    "Papad – North Indian",
                    "Pickle",
                    "Gulab Jamoon / Gajjar Halwa / Rasgullah / Malai Sandwich",
                    "Ice Cream – Vanilla",
                ],
            },
            {
                name: "North Indian Menu 3",
                items: [
                    "Starters: Veg Roll / Mini Samosa / Cheese Balls / Gobi Manchurian / Baby Corn Manchurian",
                    "Rumali Roti / Methi Chapathi / Poori / Battura",
                    "Paneer Curry / Mixed Veg Curry / Chole Masala / Rajma Masala",
                    "Aloo Mutter Dry / Aloo Gobi Dry / Aloo Capsicum Dry / Aloo Jeera Dry / Kadai Veg Dry",
                    "Veg Pulav / Peas Pulav / Jeera Pulav / Veg Biryani",
                    "Raitha",
                    "White Rice",
                    "Dal Fry / Dal Makhni",
                    "Papad – North Indian",
                    "Curd Rice / Dahi Vada",
                    "Pickle",
                    "Green Salad",
                    "Gulab Jamoon / Gajjar Halwa / Rasgullah / Malai Sandwich",
                    "Ice Cream – Vanilla",
                ],
            },
            {
                name: "North Indian Menu 4",
                items: [
                    "Welcome Drink / Soup",
                    "Starters: Veg Roll / Mini Samosa / Cheese Balls / Gobi Kabab / Aloo Kabab / Chilli Gobi / Gobi Manchurian / Baby Corn Manchurian",
                    "Veg Noodles / Pasta with Sauce",
                    "Rumali Roti / Methi Chapathi / Poori / Battura",
                    "Paneer Curry / Mixed Veg Curry / Chole Masala / Rajma Masala",
                    "Aloo Mutter Dry / Aloo Gobi Dry / Aloo Capsicum Dry / Aloo Jeera Dry / Kadai Veg Dry",
                    "Veg Pulav / Peas Pulav / Jeera Pulav / Veg Biryani",
                    "Raitha",
                    "Dal Fry / Dal Makhni",
                    "Papad – North Indian",
                    "Curd Rice / Dahi Vada",
                    "Pickle",
                    "Green Salad",
                    "Gulab Jamoon / Gajjar Halwa / Rasgullah / Malai Sandwich",
                    "Ice Cream – Vanilla",
                    "Paan",
                    "Water Bottles 300ml",
                ],
            },
            {
                name: "North Indian Menu 5",
                items: [
                    "Welcome Drink / Soup",
                    "Starters: Veg Roll / Mini Samosa / Cheese Balls / Gobi Kabab / Aloo Kabab / Chilli Gobi / Gobi Manchurian / Baby Corn Manchurian",
                    "Pani Puri / Dahi Puri",
                    "Veg Noodles / Pasta with Sauce",
                    "Rumali Roti / Methi Chapathi / Poori / Battura",
                    "Paneer Curry / Mixed Veg Curry / Chole Masala / Rajma Masala",
                    "Aloo Mutter Dry / Aloo Gobi Dry / Aloo Capsicum Dry / Aloo Jeera Dry / Kadai Veg Dry",
                    "Veg Pulav / Peas Pulav / Jeera Pulav / Veg Biryani",
                    "Raitha",
                    "Dal Fry / Dal Makhni",
                    "Papad – North Indian",
                    "Curd Rice / Dahi Vada",
                    "Pickle",
                    "Green Salad",
                    "Gulab Jamoon / Gajjar Halwa / Rasgullah / Malai Sandwich",
                    "Ice Cream – Vanilla",
                    "Paan",
                    "Water Bottles 300ml",
                ],
            },
        ],
    },
    {
        id: "seemantham",
        title: "Seemantham Menu",
        emoji: "🌸",
        description: "Traditional Tamil Nadu Seemantham (baby shower) ceremony menus",
        color: "#16A085",
        bgGradient: "from-teal-700 to-green-600",
        includes: [
            "Melamine Plates & Spoon",
            "Disposable cups for Water & Sweet",
            "Tissue Paper, Sweet Saunf, Mineral Water",
            "Food served hot in chafing dishes",
            "Buffet Setup with frill cloth",
            "OR Banana Leaf Service",
        ],
        menus: [
            {
                name: "Seemantham Menu 1",
                items: [
                    "Lime Rice / Coconut Rice",
                    "Puliyogare / Veg Pulav",
                    "Curd Rice",
                    "White Rice",
                    "Sambar",
                    "Rasam",
                    "Beans Carrot Poriyal / Cabbage Mutter Poriyal / Potato Fry",
                    "Aviyal / Kootu",
                    "Masala Vada / Chilli Baji / Onion Pakkoda / Medhu Pakkoda",
                    "Papad, Pickle",
                    "Semia Payasam",
                    "Jamoon / Gajjar Halwa / Ladoo / Badusha / Jangiri / Mysore Pak",
                ],
            },
            {
                name: "Seemantham Menu 2",
                items: [
                    "Veg Pulav / Veg Biryani / Ghee Rice",
                    "Lime Rice",
                    "Coconut Rice",
                    "Puliyogare",
                    "Curd Rice",
                    "White Rice",
                    "Sambar",
                    "Rasam",
                    "Beans Carrot Poriyal / Cabbage Mutter Poriyal / Potato Fry",
                    "Aviyal / Kootu",
                    "Masala Vada / Chilli Baji / Onion Pakkoda / Medhu Pakkoda",
                    "Papad, Pickle",
                    "Semia Payasam",
                    "Jamoon / Gajjar Halwa / Ladoo / Badusha / Jangiri / Mysore Pak",
                ],
            },
            {
                name: "Seemantham Menu 3",
                items: [
                    "Rumali Roti / Poori / Chapathi",
                    "Paneer Curry / Channa Masala / Veg Kurma",
                    "Veg Pulav / Veg Biryani / Ghee Rice",
                    "Lime Rice",
                    "Coconut Rice",
                    "Puliyogare",
                    "Curd Rice",
                    "White Rice",
                    "Sambar",
                    "Rasam",
                    "Beans Carrot Poriyal / Cabbage Mutter Poriyal / Potato Fry",
                    "Aviyal / Kootu",
                    "Masala Vada / Chilli Baji / Onion Pakkoda / Medhu Pakkoda",
                    "Papad, Pickle",
                    "Semia Payasam",
                    "Jamoon / Gajjar Halwa / Ladoo / Badusha / Jangiri / Mysore Pak",
                ],
            },
            {
                name: "Seemantham Menu 4",
                items: [
                    "Rumali Roti / Poori / Chapathi",
                    "Paneer Curry / Channa Masala / Veg Kurma",
                    "Veg Pulav / Veg Biryani / Ghee Rice",
                    "Lime Rice",
                    "Coconut Rice",
                    "Puliyogare",
                    "Curd Rice",
                    "White Rice",
                    "Sambar",
                    "Rasam",
                    "Beans Carrot Poriyal / Cabbage Mutter Poriyal / Potato Fry",
                    "Aviyal / Kootu",
                    "Masala Vada / Chilli Baji / Onion Pakkoda / Medhu Pakkoda",
                    "Papad, Pickle",
                    "Semia Payasam",
                    "Jamoon / Gajjar Halwa / Ladoo / Badusha / Jangiri / Mysore Pak",
                    "Ice Cream",
                    "Banana",
                    "Beeda",
                    "Water Bottles 300ml",
                ],
            },
        ],
    },
    {
        id: "full-contract",
        title: "Full Contract List",
        emoji: "📋",
        description: "Complete catering contract with all services included end-to-end",
        color: "#7B1C1C",
        bgGradient: "from-maroon to-red-900",
        includes: [
            "Complete Event Setup",
            "Melamine Plates & Spoon",
            "Disposable cups for Water & Sweet",
            "Tissue Paper, Sweet Saunf, Mineral Water",
            "Food served hot in chafing dishes",
            "Buffet Setup with frill cloth",
            "Banana Leaf Service Available",
            "Dedicated Event Coordinator",
        ],
        menus: [
            {
                name: "Full Contract Services",
                items: [
                    "Complete Breakfast + Lunch + Dinner",
                    "All Starters, Soups & Welcome Drinks",
                    "Full Buffet Setup & Service Staff",
                    "Dedicated Event Coordinator",
                    "Custom Menu Planning",
                    "Live Counters (Dosa, Chaat, etc.)",
                    "Dessert Counter",
                    "Beverages & Refreshments",
                    "Post-Event Cleanup",
                    "Contact us for custom pricing",
                ],
            },
        ],
    },
];
